Repository SpreadSheets600/Password-Manager, pull requests merged in 2024-10, with the labels that each got.

#2 Added requirements file
  requirements.txt
Labels: bug, hacktoberfest, hacktoberfest-accepted

#5 Update Main.py
  SRC/Main.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#9 Master Key Added
  SRC/Main.py
  SRC/__pycache__/DataBase.cpython-312.pyc
  SRC/__pycache__/Exceptions.cpython-312.pyc
  SRC/__pycache__/Utilities.cpython-312.pyc
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#11 Modified password generator
  SRC/Main.py
  SRC/__pycache__/DataBase.cpython-312.pyc
  SRC/__pycache__/Exceptions.cpython-312.pyc
  SRC/__pycache__/Utilities.cpython-312.pyc
  passwords.db
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#18 Added password strength validation
  .gitignore
  SRC/Main.py
  SRC/Utilities.py
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted

#20 Unit test for utilities.py
  SRC/Utilities.py
  SRC/__pycache__/Utilities.cpython-312.pyc
  requirements.txt
  tests/test_utilities.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#26 MAJOR UPDATE: Bug fixing and other additions
  .gitignore
  SRC/Main.py
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted
